<?php
/**
 * Created by PhpStorm.
 * User: joedie
 * Date: 2018/01/14
 * Time: 18:40
 */
require_once 'create.php';

use createSQL\createSQL;

class CreateShift extends createSQL{
    public function createShifts($month = 0){
        $from_to = $this->getStartAndEnd($month);
        $dates = $this->createDateArray($from_to);
        $this->exportSQL($dates);

    }

    public function exportSQL($dates)
    {
        parent::exportSQL($dates); // TODO: Change the autogenerated stub
        //
        $user = '3';
        $attend = '09:00';
        $clock = '18:00';
        $sql = '';
        foreach ($dates as $date){
            $sql .= "INSERT INTO `shifts` (`user_id`,`date`,`attend`,`clock`) VALUES ({$user},'{$date}','{$attend}','{$clock}');".PHP_EOL;
        }
        echo $sql;
    }
}

$date = new CreateShift();
$date->createShifts();